package ExceptioHandling;

public class Throwandexception {
	int a = 10;
	int b = 12;

	public void additionoftwonumber() throws InterruptedException {
		Thread.sleep(200);
		System.out.println(a + b);

	}

}
